In [1]:
# 1. 데이터 생성

In [ ]:
import os, json, time, re, math
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from collections import Counter
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS as LangchainFAISS
from langchain_core.documents import Document


load_dotenv()
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
MODEL = "gpt-4o-mini"
embeddings = OpenAIEmbeddings(model='text-embedding-3-small')

In [3]:
llm.invoke('안녕하세요')

AIMessage(content='안녕하세요! 어떻게 도와드릴까요?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 9, 'total_tokens': 19, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_a7190374f3', 'id': 'chatcmpl-DVYF2RNeV4cZDqCIxxbwcKlqsBV1h', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019d9a6a-7dd9-7d71-b423-aabb9aebcd01-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 9, 'output_tokens': 10, 'total_tokens': 19, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [4]:
import FinanceDataReader as fdr
etf_listing =fdr.StockListing('ETF/KR')

In [5]:
!pwd

/data/lecture/modu/llm/notebooks/week06

In [6]:
etf_listing.head()

,Symbol,Category,Name,Price,RiseFall,Change,ChangeRate,NAV,EarningRate,Volume,Amount,MarCap
0,069500,1,KODEX 200,94050,5,-660,-0.70,94029.0,33.9969,10221423,962685,213541
1,360750,4,TIGER 미국S&P500,25940,2,160,0.62,25977.0,1.3441,11532078,298601,161023
2,396500,2,TIGER 반도체TOP10,35735,5,-200,-0.56,35759.0,49.1078,8942100,319898,95198
3,133690,4,TIGER 미국나스닥100,172915,2,920,0.53,173385.0,2.7072,424825,73348,87460
4,379800,4,KODEX 미국S&P500,23705,2,145,0.62,23743.0,1.2831,20001113,473308,84852

In [7]:
etf_listing['Symbol'].astype(str).str.zfill(6)

0       069500
1       360750
2       396500
3       133690
4       379800
         ...
1088    412560
1089    334700
1090    465620
1091    306520
1092    301410
Name: Symbol, Length: 1093, dtype: object

In [8]:
name_by_ticker = dict(zip(etf_listing['Symbol'].astype(str).str.zfill(6), etf_listing['Name']))
name_by_ticker

{'069500': 'KODEX 200',
 '360750': 'TIGER 미국S&P500',
 '396500': 'TIGER 반도체TOP10',
 '133690': 'TIGER 미국나스닥100',
 '379800': 'KODEX 미국S&P500',
 '102110': 'TIGER 200',
 '459580': 'KODEX CD금리액티브(합성)',
 '488770': 'KODEX 머니마켓액티브',
 '229200': 'KODEX 코스닥150',
 '379810': 'KODEX 미국나스닥100',
 '278530': 'KODEX 200TR',
 '122630': 'KODEX 레버리지',
 '411060': 'ACE KRX금현물',
 '310970': 'TIGER MSCI Korea TR',
 '357870': 'TIGER CD금리투자KIS(합성)',
 '091160': 'KODEX 반도체',
 '498400': 'KODEX 200타겟위클리커버드콜',
 '233740': 'KODEX 코스닥150레버리지',
 '423160': 'KODEX KOFR금리액티브(합성)',
 '381180': 'TIGER 미국필라델피아반도체나스닥',
 '381170': 'TIGER 미국테크TOP10 INDXX',
 '273130': 'KODEX 종합채권(AA-이상)액티브',
 '148020': 'RISE 200',
 '360200': 'ACE 미국S&P500',
 '458730': 'TIGER 미국배당다우존스',
 '0043B0': 'TIGER 머니마켓액티브',
 '367380': 'ACE 미국나스닥100',
 '102780': 'KODEX 삼성그룹',
 '481050': 'KODEX CD1년금리플러스액티브(합성)',
 '161510': 'PLUS 고배당주',
 '455890': 'RISE 머니마켓액티브',
 '449170': 'TIGER KOFR금리액티브(합성)',
 '292150': 'TIGER 코리아TOP10',
 '395160': 'KODEX AI반도체',
 '487240': 'KODEX AI전력핵심설비',
 '278540': 'KODEX MSCI Korea TR',
 '232080': 'TIGER 코스닥150',
 '305720': 'KODEX 2차전지산업',
 '214980': 'KODEX 단기채권PLUS',
 '466920': 'SOL 조선TOP3플러스',
 '385540': 'RISE 종합채권(A-이상)액티브',
 '453850': 'ACE 미국30년국채액티브(H)',
 '294400': 'KIWOOM 200TR',
 '395270': 'HANARO Fn K-반도체',
 '449450': 'PLUS K방산',
 '488080': 'TIGER 반도체TOP10레버리지',
 '284430': 'KODEX 200미국채혼합',
 '487230': 'KODEX 미국AI전력핵심인프라',
 '329200': 'TIGER 리츠부동산인프라',
 '475630': 'TIGER CD1년금리액티브(합성)',
 '441640': 'KODEX 미국배당커버드콜액티브',
 '477080': 'RISE CD금리액티브(합성)',
 '456600': 'TIME 글로벌AI인공지능액티브',
 '0072R0': 'TIGER KRX금현물',
 '315930': 'KODEX Top5PlusTR',
 '494310': 'KODEX 반도체레버리지',
 '105190': 'ACE 200',
 '152100': 'PLUS 200',
 '0117L0': 'KODEX 26-12 금융채(AA-이상)액티브',
 '379780': 'RISE 미국S&P500',
 '486290': 'TIGER 미국나스닥100타겟데일리커버드콜',
 '368590': 'RISE 미국나스닥100',
 '371460': 'TIGER 차이나전기차SOLACTIVE',
 '144600': 'KODEX 은선물(H)',
 '157450': 'TIGER 단기통안채',
 '305540': 'TIGER 2차전지테마',
 '426030': 'TIME 미국나스닥100액티브',
 '457480': 'ACE 테슬라밸류체인액티브',
 '436140': 'SOL 종합채권(AA-이상)액티브',
 '448330': 'KODEX 삼성전자채권혼합',
 '455850': 'SOL AI반도체소부장',
 '446770': 'ACE 글로벌반도체TOP4 Plus',
 '0139F0': 'TIGER 12월자동연장금융채(AA-이상)액티브',
 '469830': 'SOL 초단기채권액티브',
 '102970': 'KODEX 증권',
 '465580': 'ACE 미국빅테크TOP7 Plus',
 '356540': 'ACE 종합채권(AA-이상)액티브',
 '139260': 'TIGER 200 IT',
 '445290': 'KODEX 로봇액티브',
 '252670': 'KODEX 200선물인버스2X',
 '451540': 'TIGER 종합채권(AA-이상)액티브',
 '476550': 'TIGER 미국30년국채커버드콜액티브(H)',
 '472150': 'TIGER 배당커버드콜액티브',
 '091230': 'TIGER 반도체',
 '466940': 'TIGER 은행고배당플러스TOP10',
 '494890': 'KODEX 200액티브',
 '0163Y0': 'KoAct 코스닥액티브',
 '434730': 'HANARO 원자력iSelect',
 '438080': 'ACE 미국S&P500미국채혼합50액티브',
 '0162Z0': 'RISE 삼성전자SK하이닉스채권혼합50',
 '497570': 'TIGER 미국필라델피아AI반도체나스닥',
 '463250': 'TIGER K방산&우주',
 '226490': 'KODEX 코스피',
 '446720': 'SOL 미국배당다우존스',
 '390390': 'KODEX 미국반도체',
 '462330': 'KODEX 2차전지산업레버리지',
 '0091P0': 'TIGER 코리아원자력',
 '114800': 'KODEX 인버스',
 '495050': 'RISE 코리아밸류업',
 '371160': 'TIGER 차이나항셍테크',
 '481060': 'KODEX 미국30년국채타겟커버드콜(합성 H)',
 '479520': 'RISE KOFR금리액티브(합성)',
 '0061Z0': 'RISE 단기특수은행채액티브',
 '462010': 'TIGER 2차전지소재Fn',
 '475720': 'RISE 200위클리커버드콜',
 '449180': 'KODEX 미국S&P500(H)',
 '402970': 'ACE 미국배당다우존스',
 '444200': 'SOL 코리아메가테크액티브',
 '251600': 'PLUS 고배당주채권혼합',
 '441800': 'TIME Korea플러스배당액티브',
 '237350': 'KODEX 코스피100',
 '069660': 'KIWOOM 200',
 '272580': 'TIGER 단기채권액티브',
 '138540': 'TIGER 현대차그룹플러스',
 '479080': '1Q 머니마켓액티브',
 '494670': 'TIGER 조선TOP10',
 '494300': 'KODEX 미국나스닥100데일리커버드콜OTM',
 '153130': 'KODEX 단기채권',
 '0117V0': 'TIGER 코리아AI전력기기TOP3플러스',
 '458760': 'TIGER 미국배당다우존스타겟커버드콜2호',
 '498410': 'KODEX 금융고배당TOP10타겟위클리커버드콜',
 '385560': 'RISE KIS국고채30년Enhanced',
 '495850': 'KODEX 코리아밸류업',
 '0105E0': 'SOL 코리아고배당',
 '314250': 'KODEX 미국빅테크10(H)',
 '364980': 'TIGER 2차전지TOP10',
 '456610': 'TIGER 미국달러SOFR금리액티브(합성)',
 '471230': 'KODEX 국고채10년액티브',
 '438100': 'ACE 미국나스닥100미국채혼합50액티브',
 '0131V0': '1Q 미국우주항공테크',
 '487340': 'ACE 머니마켓액티브',
 '455030': 'KODEX 미국달러SOFR금리액티브(합성)',
 '469150': 'ACE AI반도체TOP3+',
 '438330': 'TIGER 우량회사채액티브',
 '0025N0': 'TIGER TDF2045 적격',
 '0127P0': 'ACE 미국대형성장주액티브',
 '491010': 'TIGER 글로벌AI전력인프라액티브',
 '447770': 'TIGER 테슬라채권혼합Fn',
 '0148J0': 'TIGER 코리아휴머노이드로봇산업',
 '483280': 'KODEX 미국AI테크TOP10타겟커버드콜',
 '476800': 'KODEX 한국부동산리츠인프라',
 '484790': 'KODEX 미국30년국채액티브(H)',
 '0048J0': 'KODEX 미국머니마켓액티브',
 '114260': 'KODEX 국고채3년',
 '458250': 'TIGER 미국30년국채스트립액티브(합성 H)',
 '482730': 'TIGER 미국S&P500타겟데일리커버드콜',
 '473290': 'KODEX 26-12 회사채(AA-이상)액티브',
 '0080G0': 'KODEX 방산TOP10',
 '091180': 'KODEX 자동차',
 '480260': 'TIGER 27-04회사채(A+이상)액티브',
 '451000': 'PLUS 종합채권(AA-이상)액티브',
 '462900': 'KoAct 바이오헬스케어액티브',
 '329750': 'TIGER 미국달러단기채권액티브',
 '449190': 'KODEX 미국나스닥100(H)',
 '434060': 'KODEX TDF2050액티브 적격',
 '315960': 'RISE 대형고배당10TR',
 '474220': 'TIGER 미국테크TOP10타겟커버드콜',
 '423920': 'TIGER 미국필라델피아반도체레버리지(합성)',
 '490590': 'RISE 미국AI밸류체인데일리고정커버드콜',
 '251350': 'KODEX MSCI선진국',
 '293180': 'HANARO 200',
 '270810': 'RISE 코스닥150',
 '0167A0': 'SOL AI반도체TOP2플러스',
 '0162Y0': 'TIME 코스닥액티브',
 '295040': 'SOL 200TR',
 '448290': 'TIGER 미국S&P500(H)',
 '0052D0': 'TIGER 코리아배당다우존스',
 '0177N0': 'KODEX 삼성전자SK하이닉스채권혼합50',
 '0023A0': 'SOL 미국양자컴퓨팅TOP10',
 '469070': 'RISE AI&로봇',
 '489250': 'KODEX 미국배당다우존스',
 '471990': 'KODEX AI반도체핵심장비',
 '091170': 'KODEX 은행',
 '365780': 'ACE 국고채10년',
 '361580': 'RISE 200TR',
 '148070': 'KIWOOM 국고채10년',
 '496080': 'TIGER 코리아밸류업',
 '132030': 'KODEX 골드선물(H)',
 '277630': 'TIGER 코스피',
 '241180': 'TIGER 일본니케이225',
 '490490': 'SOL 미국배당미국채혼합50',
 '499660': 'TIGER CD금리플러스액티브(합성)',
 '157500': 'TIGER 증권',
 '484880': 'SOL 금융지주플러스고배당',
 '279530': 'KODEX 고배당주',
 '0098F0': 'KODEX 원자력SMR',
 '442580': 'PLUS 글로벌HBM반도체',
 '478150': 'TIME 글로벌우주테크&방산액티브',
 '0007F0': 'KODEX 27-12 회사채(AA-이상)액티브',
 '307520': 'TIGER 지주회사',
 '466950': 'TIGER 글로벌AI액티브',
 '385510': 'KODEX 신재생에너지액티브',
 '477050': 'PLUS 머니마켓액티브',
 '453810': 'KODEX 인도Nifty50',
 '461490': 'RISE 글로벌자산배분액티브',
 '0167Z0': 'KODEX 미국우주항공',
 '463050': 'TIME K바이오액티브',
 '0053L0': 'TIGER 차이나휴머노이드로봇',
 '433500': 'ACE 원자력TOP10',
 '139230': 'TIGER 200 중공업',
 '453870': 'TIGER 인도니프티50',
 '454780': 'KIWOOM 종합채권(AA-이상)액티브',
 '0040Y0': 'SOL 팔란티어커버드콜OTM채권혼합',
 '0046A0': 'TIGER 미국초단기(3개월이하)국채',
 '0060H0': 'TIGER 토탈월드스탁액티브',
 '472160': 'TIGER 미국테크TOP10 INDXX(H)',
 '442320': 'RISE 글로벌원자력',
 '439870': 'KODEX 국고채30년액티브',
 '0144L0': 'KODEX 미국성장커버드콜액티브',
 '456880': 'ACE 미국달러SOFR금리(합성)',
 '473330': 'SOL 미국30년국채커버드콜(합성)',
 '491620': 'RISE 미국테크100데일리고정커버드콜',
 '302450': 'RISE 코스피',
 '290130': 'RISE ESG사회책임투자',
 '475080': 'KODEX 테슬라커버드콜채권혼합액티브',
 '441680': 'TIGER 미국나스닥100커버드콜(합성)',
 '439860': 'KODEX ESG종합채권(A-이상)액티브',
 '472170': 'TIGER 미국테크TOP10채권혼합',
 '0016X0': 'SOL 중단기회사채(A-이상)액티브',
 '421320': 'PLUS 우주항공&UAM',
 '418660': 'TIGER 미국나스닥100레버리지(합성)',
 '273140': 'KODEX 단기변동금리부채권액티브',
 '448300': 'TIGER 미국나스닥100(H)',
 '481190': 'SOL 미국테크TOP10',
 '394670': 'TIGER 글로벌리튬&2차전지SOLACTIVE(합성)',
 '228790': 'TIGER 화장품',
 '451060': '1Q 200액티브',
 '245710': 'ACE 베트남VN30(합성)',
 '385720': 'TIME 코스피액티브',
 '0015B0': 'KoAct 미국나스닥성장기업액티브',
 '437080': 'KODEX 미국종합채권ESG액티브(H)',
 '435420': 'TIGER 미국나스닥100채권혼합50',
 '472870': 'RISE 미국30년국채엔화노출(합성 H)',
 '0038A0': 'KODEX 미국휴머노이드로봇',
 '363570': 'KODEX 장기종합채권(AA-이상)액티브',
 '485540': 'KODEX 미국AI테크TOP10',
 '123320': 'TIGER 레버리지',
 '0122W0': 'RISE 26-11 회사채(AA-이상)액티브',
 '0094K0': 'TIGER 28-04 회사채(A+이상)액티브',
 '244580': 'KODEX 바이오',
 '493810': 'TIGER 미국AI빅테크10타겟데일리커버드콜',
 '433330': 'SOL 미국S&P500',
 '448630': 'RISE 삼성그룹Top3채권혼합',
 '476760': 'ACE 미국30년국채액티브',
 '0101N0': 'RISE AI전력인프라',
 '385550': 'RISE 단기채권알파액티브',
 '213610': 'KODEX 삼성그룹밸류',
 '283580': 'KODEX 차이나CSI300',
 '458260': 'TIGER 미국투자등급회사채액티브(H)',
 '364970': 'TIGER 바이오TOP10',
 '489030': 'PLUS 고배당주위클리커버드콜',
 '0093A0': 'RISE AI반도체TOP10',
 '473460': 'KODEX 미국서학개미',
 '310960': 'TIGER 200TR',
 '488980': 'SOL 26-12 회사채(AA-이상)액티브',
 '495230': 'KoAct 코리아밸류업액티브',
 '0051G0': 'SOL 미국원자력SMR',
 '486450': 'SOL 미국AI전력인프라',
 '233160': 'TIGER 코스닥150 레버리지',
 '0026S0': '1Q 미국S&P500',
 '422420': 'RISE 2차전지액티브',
 '302190': 'TIGER 중장기국채',
 '0047A0': 'TIGER 차이나테크TOP10',
 '463290': '1Q 단기금융채액티브',
 '196230': 'RISE 단기통안채',
 '0000J0': 'PLUS 한화그룹주',
 '0052S0': '1Q 미국S&P500미국채혼합50액티브',
 '0064K0': 'KODEX 금액티브',
 '329650': 'KODEX TRF3070',
 '498270': 'KIWOOM 미국양자컴퓨팅',
 '461950': 'KODEX 2차전지핵심소재10',
 '448540': 'ACE 엔비디아채권혼합',
 '0153K0': 'KODEX 주주환원고배당주',
 '0089D0': 'KODEX 금융고배당TOP10',
 '266160': 'RISE 고배당',
 '426020': 'TIME 미국S&P500액티브',
 '354500': 'ACE 코스닥150',
 '261260': 'KODEX 미국달러선물인버스2X',
 '305080': 'TIGER 미국채10년선물',
 '409820': 'KODEX 미국나스닥100레버리지(합성 H)',
 '466930': 'SOL 자동차TOP3플러스',
 '271050': 'KODEX WTI원유선물인버스(H)',
 '474590': 'WON 반도체밸류체인액티브',
 '483320': 'ACE 엔비디아밸류체인액티브',
 '0048K0': 'KODEX 차이나휴머노이드로봇',
 '472920': 'HK 종합채권(AA-이상)액티브',
 '332930': 'HANARO 200TR',
 '497880': 'SOL CD금리&머니마켓액티브',
 '476450': 'KIWOOM 머니마켓액티브',
 '0043Y0': 'TIME 차이나AI테크액티브',
 '0040X0': 'SOL 팔란티어미국채커버드콜혼합',
 '396520': 'TIGER 차이나반도체FACTSET',
 '367760': 'RISE 네트워크인프라',
 '117700': 'KODEX 건설',
 '388420': 'RISE 비메모리반도체액티브',
 '491610': '1Q CD금리액티브(합성)',
 '160580': 'TIGER 구리실물',
 '272560': 'RISE 단기국공채액티브',
 '200250': 'KIWOOM 인도Nifty50(합성)',
 '490090': 'TIGER 미국AI빅테크10',
 '0173Y0': 'KODEX 미국AI광통신네트워크',
 '190620': 'ACE 단기통안채',
 '0008S0': 'TIGER 미국배당다우존스타겟데일리커버드콜',
 '0123G0': 'TIGER 미국AI전력SMR',
 '267770': 'TIGER 200선물레버리지',
 '496020': 'WON 전단채플러스액티브',
 '471040': 'KoAct 글로벌AI&로봇액티브',
 '414780': 'TIGER 차이나과창판STAR50(합성)',
 '452360': 'SOL 미국배당다우존스(H)',
 '0111P0': '1Q 미국나스닥100미국채혼합50액티브',
 '461270': 'ACE 26-06 회사채(AA-이상)액티브',
 '471760': 'TIGER AI반도체핵심공정',
 '143860': 'TIGER 헬스케어',
 '0167B0': 'SOL 200타겟위클리커버드콜',
 '0092B0': 'SOL 한국원자력SMR',
 '0092C0': 'SOL 27-12 회사채(AA-이상)액티브',
 '412570': 'TIGER 2차전지TOP10레버리지',
 '483340': 'ACE 구글밸류체인액티브',
 '0005D0': 'SOL 전고체배터리&실리콘음극재',
 '464240': 'KIWOOM 26-09회사채(AA-이상)액티브',
 '332500': 'ACE 200TR',
 '0080Y0': 'SOL 조선TOP3플러스레버리지',
 '325020': 'KODEX 배당가치',
 '304660': 'KODEX 미국30년국채울트라선물(H)',
 '0019K0': 'TIME 미국나스닥100채권혼합50액티브',
 '480020': 'ACE 미국빅테크7+데일리타겟커버드콜(합성)',
 '455860': 'SOL 2차전지소부장Fn',
 '237370': 'KODEX 코리아배당성장채권혼합',
 '325010': 'KODEX 성장주',
 '251340': 'KODEX 코스닥150선물인버스',
 '458210': 'KIWOOM CD금리액티브(합성)',
 '0001S0': 'TIGER 26-04 회사채(A+이상)액티브',
 '0115D0': 'KODEX 조선TOP10',
 '0091C0': 'KODEX 미국10년국채액티브(H)',
 '139220': 'TIGER 200 건설',
 '0119H0': 'KODEX 28-12 회사채(AA-이상)액티브',
 '495060': 'TIME 코리아밸류업액티브',
 '0104N0': 'TIGER 200타겟위클리커버드콜',
 '243880': 'TIGER 200IT레버리지',
 '442570': 'RISE TDF2050액티브 적격',
 '114100': 'RISE 국고채3년',
 '403790': '마이다스 코스피액티브',
 '192090': 'TIGER 차이나CSI300',
 '429000': 'TIGER 미국S&P500배당귀족',
 '0005A0': 'KODEX 미국S&P500데일리커버드콜OTM',
 '0162M0': 'KODEX 금융채1~2년(AA-이상)PLUS액티브',
 '451530': 'TIGER 국고채30년스트립액티브',
 '372330': 'KODEX 차이나항셍테크',
 '377990': 'TIGER Fn신재생에너지',
 '182480': 'TIGER 미국MSCI리츠(합성 H)',
 '219480': 'KODEX 미국S&P500선물(H)',
 '480030': 'ACE 미국500데일리타겟커버드콜(합성)',
 '0138Y0': 'PLUS 금채권혼합',
 '494220': 'UNICORN SK하이닉스밸류체인액티브',
 '483290': 'KODEX 미국배당다우존스타겟커버드콜',
 '136340': 'RISE 중기우량회사채',
 '495550': 'SOL 코리아밸류업TR',
 '367770': 'RISE 수소경제테마',
 '319640': 'TIGER 골드선물(H)',
 '481180': 'SOL 미국AI소프트웨어',
 '411420': 'KODEX 미국나스닥AI테크액티브',
 '491820': 'HANARO 전력설비투자',
 '438570': 'SOL 국고채10년',
 '245340': 'TIGER 미국다우존스30',
 '0099L0': 'ACE 우량회사채(AA-이상)액티브',
 '0074K0': 'KoAct K수출핵심기업TOP30액티브',
 '457990': 'PLUS 태양광&ESS',
 '152870': '파워 200',
 '465610': 'ACE 미국빅테크TOP7 Plus레버리지(합성)',
 '464930': 'TIGER 글로벌혁신블루칩TOP10',
 '309230': 'ACE 미국WideMoat동일가중',
 '0151P0': 'RISE 코리아전략산업액티브',
 '114820': 'TIGER 국채3년',
 '469170': 'ACE 포스코그룹포커스',
 '433980': 'KODEX TDF2040액티브 적격',
 '490480': 'SOL K방산',
 '363580': 'KODEX 200IT TR',
 '423170': 'SOL 글로벌AI반도체탑픽액티브',
 '130730': 'KIWOOM 단기자금',
 '475050': 'ACE KPOP포커스',
 '0151S0': 'KODEX 미국AI반도체TOP3플러스',
 '0069M0': '1Q 미국나스닥100',
 '0066W0': 'SOL 국제금',
 '0168K0': 'TIGER 기술이전바이오액티브',
 '488500': 'TIGER 미국S&P500동일가중',
 '168580': 'ACE 중국본토CSI300',
 '328370': 'PLUS 코스피TR',
 '0127M0': 'ACE 미국대형가치주액티브',
 '491230': 'PLUS 국공채머니마켓액티브',
 '0131W0': '1Q 단기특수은행채액티브',
 '0118Z0': 'ACE 미국AI테크핵심산업액티브',
 '464310': 'TIGER 글로벌AI&로보틱스 INDXX',
 '0082V0': 'KODEX TDF2060액티브 적격',
 '0132K0': 'PLUS 테슬라위클리커버드콜채권혼합',
 '465780': '마이티 26-09 특수채(AAA)액티브',
 '0000Y0': 'HK 26-12 회사채(AA-이상)액티브',
 '278240': 'RISE 코스닥150선물레버리지',
 '204480': 'TIGER 차이나CSI300레버리지(합성)',
 '394660': 'TIGER 글로벌자율주행&전기차SOLACTIVE',
 '261270': 'KODEX 미국달러선물인버스',
 '490600': 'RISE 미국배당100데일리고정커버드콜',
 '0176E0': 'RISE 미국AI전력인프라액티브',
 '399110': 'SOL 미국S&P500ESG',
 '0085N0': 'ACE 미국10년국채액티브(H)',
 '480040': 'ACE 미국반도체데일리타겟커버드콜(합성)',
 '454320': 'HANARO CAPEX설비투자iSelect',
 '157490': 'TIGER 소프트웨어',
 '448100': 'WON 200',
 '496090': 'KIWOOM 코리아밸류업',
 '304940': 'KODEX 미국나스닥100선물(H)',
 '473640': 'HANARO 글로벌금채굴기업',
 '481430': 'RISE 국고채10년액티브',
 '498180': '파워 종합채권(AA-이상)액티브',
 '495330': '1Q 코리아밸류업',
 '0183J0': 'TIGER 미국우주테크',
 '0094M0': 'RISE 코리아밸류업위클리고정커버드콜',
 '228810': 'TIGER 미디어컨텐츠',
 '337160': 'KODEX 200ESG',
 '479730': 'TIGER 인도빌리언컨슈머',
 '211900': 'KODEX 코리아배당성장',
 '364960': 'TIGER BBIG',
 '495710': 'BNK 26-06 특수채(AAA이상)액티브',
 '304780': 'HANARO 200선물레버리지',
 '0135Y0': 'ITF 중기종합채권(AA-이상)액티브',
 '401170': 'RISE 메타버스',
 '0036R0': 'RISE 미국휴머노이드로봇',
 '308620': 'KODEX 미국10년국채선물',
 '359210': 'KODEX 코스피TR',
 '0115E0': 'KODEX 코리아소버린AI',
 '138520': 'TIGER 삼성그룹',
 '468380': 'KODEX iShares미국하이일드액티브',
 '461500': 'HANARO 종합채권(AA-이상)액티브',
 '0091M0': 'HANARO 27-06 회사채(AA-이상)액티브',
 '447620': 'SOL 미국TOP5채권혼합50',
 '0098N0': 'PLUS 자사주매입고배당주',
 '441540': 'HANARO Fn조선해운',
 '122090': 'PLUS 코스피50',
 '0018C0': 'PLUS 고배당주위클리고정커버드콜',
 '0132H0': 'KODEX 미국원자력SMR',
 '329660': 'KODEX TRF5050',
 '0035T0': 'PLUS 글로벌휴머노이드로봇액티브',
 '332940': 'HANARO MSCI Korea TR',
 '211560': 'TIGER 배당성장',
 '203780': 'TIGER 미국나스닥바이오',
 '0113D0': 'TIME 글로벌탑픽액티브',
 '195980': 'PLUS 신흥국MSCI(합성 H)',
 '143850': 'TIGER 미국S&P500선물(H)',
 '0111J0': 'HANARO 증권고배당TOP3플러스',
 '476850': 'KoAct 배당성장액티브',
 '108450': 'ACE 삼성그룹섹터가중',
 '471780': 'TIGER 코리아테크액티브',
 '0085P0': 'ACE 미국10년국채액티브',
 '453330': 'RISE 미국S&P500(H)',
 '266420': 'KODEX 헬스케어',
 '210780': 'TIGER 코스피고배당',
 '492500': '1Q 현대차그룹채권(A+이상)&국고통안',
 '326240': 'RISE IT플러스',
 '269540': 'PLUS 미국S&P500(H)',
 '494330': 'ACE 라이프자산주주가치액티브',
 '0086B0': 'TIGER 리츠부동산인프라TOP10액티브',
 '0102A0': 'TIGER 미국AI소프트웨어TOP4Plus',
 '261220': 'KODEX WTI원유선물(H)',
 '473440': 'ACE 11월만기자동연장회사채AA-이상액티브',
 '412770': 'TIGER 글로벌AI플랫폼액티브',
 '0052T0': '1Q 중단기회사채(A-이상)액티브',
 '0017Y0': '1Q 종합채권(AA-이상)액티브',
 '465330': 'RISE 2차전지TOP10',
 '476030': 'SOL 미국나스닥100',
 '228800': 'TIGER 여행레저',
 '329670': 'KODEX TRF7030',
 '475300': 'SOL 반도체전공정',
 '0007N0': '아이엠에셋 200',
 '440910': 'WON 미국우주항공방산',
 '460960': 'ACE 글로벌인컴TOP10',
 '0100K0': 'KODEX 방산TOP10레버리지',
 '272910': 'ACE 중장기국공채액티브',
 '0049M0': 'ACE 미국배당퀄리티+커버드콜액티브',
 '252400': 'RISE 200선물레버리지',
 '0022T0': 'SOL 국제금커버드콜액티브',
 '0089C0': 'KODEX 미국S&P500변동성확대시커버드콜',
 '475310': 'SOL 반도체후공정',
 '433970': 'KODEX TDF2030액티브 적격',
 '486240': 'DAISHIN343 AI반도체&인프라액티브',
 '491700': 'HK 200',
 '0142D0': 'TIGER 미국AI데이터센터TOP4Plus',
 '461460': 'PLUS 국고채10년액티브',
 '401470': 'KODEX 메타버스액티브',
 '0005G0': 'ITF K-AI반도체코어테크',
 '476750': 'ACE 미국30년국채엔화노출액티브(H)',
 '494840': 'TIGER 미국방산TOP10',
 '261070': 'TIGER 코스닥150바이오테크',
 '485690': 'RISE 미국AI밸류체인TOP3Plus',
 '261240': 'KODEX 미국달러선물',
 '445150': 'KODEX 친환경조선해운액티브',
 '0021E0': 'ACE TDF2050액티브 적격',
 '306950': 'KODEX KRX300레버리지',
 '0041D0': 'KODEX 미국AI소프트웨어TOP10',
 '475280': 'ACE 8월만기자동연장회사채AA-이상액티브',
 '456680': 'TIGER 차이나전기차레버리지(합성)',
 '298340': 'PLUS 국채선물3년',
 '495040': 'PLUS 코리아밸류업',
 '0154F0': 'WON 초대형IB&금융지주',
 '453080': 'KIWOOM 미국나스닥100(H)',
 '444490': 'WON 미국S&P500',
 '463680': 'KODEX 미국S&P500테크놀로지',
 '337140': 'KODEX 코스피대형주',
 '150460': 'TIGER 중국소비테마',
 '0008T0': 'SOL 화장품TOP3플러스',
 '298770': 'KODEX 한국대만IT프리미어',
 '419890': 'KIWOOM 단기채권ESG액티브',
 '440640': 'ACE 단기채권알파액티브',
 '475350': 'RISE 버크셔포트폴리오TOP10',
 '0139P0': 'ACE 고배당주',
 '292190': 'KODEX KRX300',
 '266370': 'KODEX IT',
 '0000Z0': 'RISE 바이오TOP10액티브',
 '225040': 'TIGER 미국S&P500레버리지(합성 H)',
 '434960': 'DAISHIN343 K200',
 '0104H0': 'KoAct 미국나스닥채권혼합50액티브',
 '488720': 'WON 종합채권(AA-이상)액티브',
 '0041E0': 'KODEX 미국S&P500액티브',
 '487750': 'BNK 온디바이스AI',
 '447430': 'ACE 주주환원가치주액티브',
 '0057H0': 'PLUS 미국S&P500미국채혼합50액티브',
 '415920': 'PLUS 글로벌희토류&전략자원생산기업',
 '275980': 'TIGER 글로벌4차산업혁신기술(합성 H)',
 '0080X0': 'SOL 미국S&P500미국채혼합50',
 '365040': 'TIGER AI코리아그로스액티브',
 '473590': 'ACE 미국주식베스트셀러',
 '0000D0': 'TIGER 엔비디아미국채커버드콜밸런스(합성)',
 '495750': 'HANARO 코리아밸류업',
 '0123S0': 'HANARO 26-12 은행채(AA+이상)액티브',
 '371470': 'TIGER 차이나바이오테크SOLACTIVE',
 '458030': 'WON 국공채머니마켓액티브',
 '278620': 'PLUS 단기채권액티브',
 '455660': 'ACE 미국하이일드액티브(H)',
 '486830': 'HANARO 머니마켓액티브',
 '400970': 'TIGER Fn메타버스',
 '0068M0': 'KODEX 미국S&P500버퍼6월액티브',
 '0007G0': 'PLUS 글로벌원자력밸류체인',
 '455960': 'RISE 미국달러SOFR금리액티브(합성)',
 '498860': 'RISE 코리아금융고배당',
 '218420': 'KODEX 미국S&P500에너지(합성)',
 '453640': 'KODEX 미국S&P500헬스케어',
 '472830': 'RISE 미국30년국채커버드콜(합성)',
 '458750': 'TIGER 미국배당다우존스타겟커버드콜1호',
 '139320': 'TIGER 금은선물(H)',
 '101280': 'KODEX 일본TOPIX100',
 '277640': 'TIGER 코스피대형주',
 '152500': 'ACE 레버리지',
 '139280': 'TIGER 경기방어',
 '449770': 'KIWOOM 미국S&P500',
 '365000': 'TIGER 인터넷TOP10',
 '316670': 'KIWOOM 코스닥150',
 '0067V0': 'TIGER 차이나글로벌리더스TOP3+',
 '352540': 'KODEX 일본부동산리츠(H)',
 '395170': 'KODEX Top10동일가중',
 '256750': 'KODEX 차이나심천ChiNext(합성)',
 '295020': 'RISE 국채선물10년인버스',
 '426150': 'WON 대한민국국고채액티브',
 '0118S0': 'SOL 미국넥스트테크TOP10액티브',
 '375770': 'KODEX 탄소효율그린뉴딜',
 '452250': 'ACE 미국30년국채선물레버리지(합성 H)',
 '0046Y0': 'ACE 미국배당퀄리티',
 '0113P0': 'HK 머니마켓액티브',
 '140700': 'KODEX 보험',
 '114470': 'KIWOOM 국고채3년',
 '0098Z0': 'FOCUS 200',
 '104530': 'KIWOOM 고배당',
 '252650': 'KODEX 200동일가중',
 '322410': 'HANARO K고배당',
 '438560': 'SOL 국고채3년',
 '474800': 'KIWOOM 미국원유에너지기업',
 '475260': 'ACE 2월만기자동연장회사채AA-이상액티브',
 '138910': 'KODEX 구리선물(H)',
 '491220': 'PLUS 200TR',
 '200030': 'KODEX 미국S&P500산업재(합성)',
 '253250': 'KIWOOM 200선물레버리지',
 '433880': 'PLUS TDF2060액티브 적격',
 '496770': 'PLUS 글로벌방산',
 '123310': 'TIGER 인버스',
 '450910': 'SOL 코스닥150',
 '0020H0': 'KoAct 글로벌양자컴퓨팅액티브',
 '428510': 'KODEX 차이나AI테크액티브',
 '0152E0': 'SOL 배당성향탑픽액티브',
 '469060': 'RISE 미국반도체NYSE',
 '322400': 'HANARO e커머스',
 '448570': 'FOCUS AI코리아액티브',
 '475070': 'KoAct 글로벌친환경전력인프라액티브',
 '253150': 'PLUS 200선물레버리지',
 '407830': '에셋플러스 글로벌플랫폼액티브',
 '453950': 'TIGER TSMC파운드리밸류체인',
 '495940': 'RISE 미국AI테크액티브',
 '266360': 'KODEX K콘텐츠',
 '0166N0': 'PLUS 코스닥150액티브',
 '139270': 'TIGER 200 금융',
 '276990': 'KODEX 글로벌로봇(합성)',
 '410870': 'TIME K컬처액티브',
 '465350': 'RISE 2차전지TOP10인버스(합성)',
 '453650': 'KODEX 미국S&P500금융',
 '475270': 'ACE 5월만기자동연장회사채AA-이상액티브',
 '385590': 'ACE ESG액티브',
 '464470': 'PLUS 미국채30년액티브',
 '480310': 'TIGER 글로벌온디바이스AI',
 '292560': 'TIGER 일본엔선물',
 '479850': 'HANARO K-뷰티',
 '395290': 'HANARO Fn K-POP&미디어',
 '122260': 'KIWOOM 통안채1년',
 '0166S0': 'PLUS K제조업핵심기업액티브',
 '0083S0': '1Q 미국메디컬AI',
 '440650': 'ACE 미국달러단기채권액티브',
 '174360': 'RISE 중국본토대형주CSI100',
 '0180V0': 'ACE 미국우주테크액티브',
 '489290': 'WON 미국빌리어네어',
 '419430': 'KODEX 차이나2차전지MSCI(합성)',
 '461340': 'HANARO 글로벌생성형AI액티브',
 '476690': 'TIGER 글로벌비만치료제TOP2Plus',
 '0141S0': 'SOL 조선기자재',
 '476070': 'KODEX 글로벌비만치료제TOP2 Plus',
 '336160': 'RISE 금융채액티브',
 '0172V0': '1Q 은액티브',
 '437070': 'KODEX 아시아달러채권ESG플러스액티브',
 '140950': '파워 코스피100',
 '261140': 'TIGER 우선주',
 '252710': 'TIGER 200선물인버스2X',
 '429760': 'PLUS 미국S&P500',
 '099140': 'KODEX 차이나H',
 '0104P0': 'TIGER 코리아배당다우존스위클리커버드콜',
 '0040S0': 'HANARO 글로벌피지컬AI액티브',
 '275300': 'KODEX 우량주',
 '479620': 'SOL 미국AI반도체칩메이커',
 '442260': '마이티 다이나믹퀀트액티브',
 '261120': 'TIGER 미국달러선물인버스2X',
 '305050': 'ACE 코스피',
 '261060': 'TIGER 코스닥150IT',
 '196030': 'ACE 일본TOPIX레버리지(H)',
 '139250': 'TIGER 200 에너지화학',
 '238720': 'ACE 일본Nikkei225(H)',
 '245360': 'TIGER 차이나HSCEI',
 '152380': 'KODEX 국채선물10년',
 '0150K0': 'KoAct 수소전력ESS인프라액티브',
 '0155M0': 'ACE 미국SMR원자력TOP10',
 '276970': 'KODEX 미국S&P500배당귀족커버드콜(합성 H)',
 '147970': 'TIGER 모멘텀',
 '117460': 'KODEX 에너지화학',
 '195930': 'TIGER 유로스탁스50(합성 H)',
 '449780': 'KIWOOM 미국S&P500(H)',
 '0047R0': 'RISE 팔란티어고정테크100',
 '414270': 'ACE 글로벌자율주행액티브',
 '0023B0': 'PLUS 미국양자컴퓨팅TOP10',
 '459750': 'RISE 글로벌주식분산액티브',
 '0137V0': 'KIWOOM 미국S&P500모멘텀',
 '360140': 'KODEX 200롱코스닥150숏선물',
 '241390': 'RISE V&S셀렉트밸류채권혼합',
 '156080': 'KODEX MSCI Korea',
 '261250': 'KODEX 미국달러선물레버리지',

In [9]:
tickers_info = {
    "069500": {"category": "국내주식", "expense_ratio": 0.15, "dividend_yield": 1.8,
               "keywords": ["코스피", "대형주", "인덱스", "분산투자", "국내주식"]},
    "379800": {"category": "해외주식", "expense_ratio": 0.05, "dividend_yield": 0.0,
               "keywords": ["미국", "S&P500", "대형주", "성장", "해외주식"]},
    "411060": {"category": "배당",     "expense_ratio": 0.01, "dividend_yield": 3.5,
               "keywords": ["미국", "배당", "배당성장", "저비용", "안정"]},
    "305540": {"category": "테마",     "expense_ratio": 0.45, "dividend_yield": 0.0,
               "keywords": ["2차전지", "배터리", "테마", "성장", "고위험"]},
    "379810": {"category": "해외주식", "expense_ratio": 0.07, "dividend_yield": 0.0,
               "keywords": ["미국", "나스닥", "기술주", "성장", "IT"]},
    "381180": {"category": "해외주식", "expense_ratio": 0.49, "dividend_yield": 0.0,
               "keywords": ["반도체", "AI", "미국", "기술주", "고위험"]},
    "132030": {"category": "원자재",   "expense_ratio": 0.68, "dividend_yield": 0.0,
               "keywords": ["금", "원자재", "인플레이션", "헤지", "안전자산"]},
    "167860": {"category": "채권",     "expense_ratio": 0.15, "dividend_yield": 2.8,
               "keywords": ["채권", "국고채", "안전", "이자", "저위험"]},
    "214980": {"category": "채권",     "expense_ratio": 0.05, "dividend_yield": 3.2,
               "keywords": ["단기채", "안전", "예금대안", "저위험", "이자"]},
    "329200": {"category": "부동산",   "expense_ratio": 0.29, "dividend_yield": 4.2,
               "keywords": ["리츠", "부동산", "배당", "인프라", "실물자산"]},
    "284430": {"category": "혼합",     "expense_ratio": 0.09, "dividend_yield": 1.5,
               "keywords": ["혼합", "자산배분", "균형", "중위험", "분산투자"]},
    "371460": {"category": "해외주식", "expense_ratio": 0.49, "dividend_yield": 0.0,
               "keywords": ["중국", "전기차", "테마", "해외주식", "고위험"]},
}

In [10]:
for t, info in tickers_info.items():
    name = name_by_ticker.get(t, "(이름 미확인)")
    print(f" {t} | {name:30s} | {info['category']}")

 069500 | KODEX 200                      | 국내주식
 379800 | KODEX 미국S&P500                 | 해외주식
 411060 | ACE KRX금현물                     | 배당
 305540 | TIGER 2차전지테마                   | 테마
 379810 | KODEX 미국나스닥100                 | 해외주식
 381180 | TIGER 미국필라델피아반도체나스닥            | 해외주식
 132030 | KODEX 골드선물(H)                  | 원자재
 167860 | KIWOOM 국고채10년레버리지              | 채권
 214980 | KODEX 단기채권PLUS                 | 채권
 329200 | TIGER 리츠부동산인프라                 | 부동산
 284430 | KODEX 200미국채혼합                 | 혼합
 371460 | TIGER 차이나전기차SOLACTIVE          | 해외주식

In [11]:
def collect_etf_price(ticker, days= 365):
    end_date = datetime.now().strftime('%Y-%m-%d')
    start_date = ( datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d')
    df = fdr.DataReader(ticker, start_date, end_date)
    return {'status' : 'real', 'data' : df, 'ticker' : ticker}

In [12]:
def compute_metrics(df):
    close = df['Close'].ffill()
    ret = close.pct_change().dropna()
    ann_ret = ((1 + ret.mean()) ** 252 -1)*100
    ann_vol = ret.std() * np.sqrt(252) * 100
    cum = (1 + ret).cumprod()
    mdd = ((cum - cum.cummax()) / cum.cummax()).min() * 100
    return {'return_1y' : round(ann_ret, 2), 'volatility' : round(ann_vol,2), 'mdd' : round(mdd, 2)}

In [13]:
def risk_from_vol(vol):
    if vol < 5 : return "낮음"
    if vol < 15: return "약간 낮음"
    if vol < 25: return "중간"
    return "높음"

In [14]:
tickers_info

{'069500': {'category': '국내주식',
  'expense_ratio': 0.15,
  'dividend_yield': 1.8,
  'keywords': ['코스피', '대형주', '인덱스', '분산투자', '국내주식']},
 '379800': {'category': '해외주식',
  'expense_ratio': 0.05,
  'dividend_yield': 0.0,
  'keywords': ['미국', 'S&P500', '대형주', '성장', '해외주식']},
 '411060': {'category': '배당',
  'expense_ratio': 0.01,
  'dividend_yield': 3.5,
  'keywords': ['미국', '배당', '배당성장', '저비용', '안정']},
 '305540': {'category': '테마',
  'expense_ratio': 0.45,
  'dividend_yield': 0.0,
  'keywords': ['2차전지', '배터리', '테마', '성장', '고위험']},
 '379810': {'category': '해외주식',
  'expense_ratio': 0.07,
  'dividend_yield': 0.0,
  'keywords': ['미국', '나스닥', '기술주', '성장', 'IT']},
 '381180': {'category': '해외주식',
  'expense_ratio': 0.49,
  'dividend_yield': 0.0,
  'keywords': ['반도체', 'AI', '미국', '기술주', '고위험']},
 '132030': {'category': '원자재',
  'expense_ratio': 0.68,
  'dividend_yield': 0.0,
  'keywords': ['금', '원자재', '인플레이션', '헤지', '안전자산']},
 '167860': {'category': '채권',
  'expense_ratio': 0.15,
  'dividend_yield': 2.8,
  'keywords': ['채권', '국고채', '안전', '이자', '저위험']},
 '214980': {'category': '채권',
  'expense_ratio': 0.05,
  'dividend_yield': 3.2,
  'keywords': ['단기채', '안전', '예금대안', '저위험', '이자']},
 '329200': {'category': '부동산',
  'expense_ratio': 0.29,
  'dividend_yield': 4.2,
  'keywords': ['리츠', '부동산', '배당', '인프라', '실물자산']},
 '284430': {'category': '혼합',
  'expense_ratio': 0.09,
  'dividend_yield': 1.5,
  'keywords': ['혼합', '자산배분', '균형', '중위험', '분산투자']},
 '371460': {'category': '해외주식',
  'expense_ratio': 0.49,
  'dividend_yield': 0.0,
  'keywords': ['중국', '전기차', '테마', '해외주식', '고위험']}}

In [15]:
etf_data =[]
for t, info in tickers_info.items():
    result = collect_etf_price(t, days=365)
    # {'status' : 'real', 'data' : df, 'ticker' : ticker}
    metrics = compute_metrics(result['data'])
    name = name_by_ticker.get(t, f"ETF_{t}")
    etf_data.append({
        "ticker" : t,
        "name" : name,
        **info,
        **metrics,
        'risk_level' : risk_from_vol(metrics['volatility']),
        'data_staus' : result['status']
    })

In [16]:
etf_data[:2]

[{'ticker': '069500',
  'name': 'KODEX 200',
  'category': '국내주식',
  'expense_ratio': 0.15,
  'dividend_yield': 1.8,
  'keywords': ['코스피', '대형주', '인덱스', '분산투자', '국내주식'],
  'return_1y': np.float64(221.8),
  'volatility': np.float64(36.6),
  'mdd': np.float64(-20.62),
  'risk_level': '높음',
  'data_staus': 'real'},
 {'ticker': '379800',
  'name': 'KODEX 미국S&P500',
  'category': '해외주식',
  'expense_ratio': 0.05,
  'dividend_yield': 0.0,
  'keywords': ['미국', 'S&P500', '대형주', '성장', '해외주식'],
  'return_1y': np.float64(42.41),
  'volatility': np.float64(13.32),
  'mdd': np.float64(-5.7),
  'risk_level': '약간 낮음',
  'data_staus': 'real'}]

In [17]:
def generate_description(etf):
    
    prompt = f"""다음 ETF의 특징을 한국어 1~2문장으로 간결히 설명하세요.
    이름 : {etf['name']}
    카테고리 : {etf['category']}
    키워드 : {','.join(etf['keywords'])}
    수수료 : {etf['expense_ratio']}% / 배당수익률: {etf['dividend_yield']}$
    1년수익률 : {etf['return_1y']}% / 변동성: {etf['volatility']}% / MDDD : {etf['mdd']}%
    """
    
    return llm.invoke([{'role' : 'user', 'content' : prompt}]).content.strip()

In [18]:
documents = []
for etf in etf_data:
    desc = generate_description(etf)
    text = (f"{etf['name']} ({etf['category']}): {desc} "
            f"키워드: {', '.join(etf['keywords'])}"
            f"수수료 {etf['expense_ratio']}%, 배당수익률: {etf['dividend_yield']}%"
            f"수익률 : {etf['return_1y']}% / 변동성: {etf['volatility']}% / MDDD : {etf['mdd']}%")
    
    metadata = {k:v for k, v in etf.items() if k!="keywords"}
    metadata['keywords'] = ', '.join(etf['keywords'])
    
    documents.append(Document(page_content=text, metadata = metadata))

In [19]:
documents

[Document(metadata={'ticker': '069500', 'name': 'KODEX 200', 'category': '국내주식', 'expense_ratio': 0.15, 'dividend_yield': 1.8, 'return_1y': np.float64(221.8), 'volatility': np.float64(36.6), 'mdd': np.float64(-20.62), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '코스피, 대형주, 인덱스, 분산투자, 국내주식'}, page_content='KODEX 200 (국내주식): KODEX 200은 코스피 대형주에 투자하는 국내주식 인덱스 ETF로, 분산투자를 통해 안정성을 추구하며, 1년 수익률이 221.8%로 높은 성과를 기록하고 있습니다. 수수료는 0.15%이며, 배당수익률은 1.8%입니다. 키워드: 코스피, 대형주, 인덱스, 분산투자, 국내주식수수료 0.15%, 배당수익률: 1.8%수익률 : 221.8% / 변동성: 36.6% / MDDD : -20.62%'),
 Document(metadata={'ticker': '379800', 'name': 'KODEX 미국S&P500', 'category': '해외주식', 'expense_ratio': 0.05, 'dividend_yield': 0.0, 'return_1y': np.float64(42.41), 'volatility': np.float64(13.32), 'mdd': np.float64(-5.7), 'risk_level': '약간 낮음', 'data_staus': 'real', 'keywords': '미국, S&P500, 대형주, 성장, 해외주식'}, page_content='KODEX 미국S&P500 (해외주식): KODEX 미국S&P500 ETF는 미국의 S&P500 지수를 추종하는 해외주식 ETF로, 대형주 중심의 성장주에 투자합니다. 수수료는 0.05%이며, 최근 1년간 수익률은 42.41%로 높은 성과를 보였지만 변동성은 13.32%로 다소 존재합니다. 키워드: 미국, S&P500, 대형주, 성장, 해외주식수수료 0.05%, 배당수익률: 0.0%수익률 : 42.41% / 변동성: 13.32% / MDDD : -5.7%'),
 Document(metadata={'ticker': '411060', 'name': 'ACE KRX금현물', 'category': '배당', 'expense_ratio': 0.01, 'dividend_yield': 3.5, 'return_1y': np.float64(59.23), 'volatility': np.float64(32.95), 'mdd': np.float64(-22.76), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '미국, 배당, 배당성장, 저비용, 안정'}, page_content='ACE KRX금현물 (배당): ACE KRX금현물 ETF는 미국 배당주에 투자하며, 저비용으로 안정적인 배당 성장을 추구합니다. 현재 배당수익률은 3.5%이며, 최근 1년간 59.23%의 수익률을 기록했습니다. 키워드: 미국, 배당, 배당성장, 저비용, 안정수수료 0.01%, 배당수익률: 3.5%수익률 : 59.23% / 변동성: 32.95% / MDDD : -22.76%'),
 Document(metadata={'ticker': '305540', 'name': 'TIGER 2차전지테마', 'category': '테마', 'expense_ratio': 0.45, 'dividend_yield': 0.0, 'return_1y': np.float64(102.47), 'volatility': np.float64(47.5), 'mdd': np.float64(-23.19), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '2차전지, 배터리, 테마, 성장, 고위험'}, page_content='TIGER 2차전지테마 (테마): TIGER 2차전지테마 ETF는 2차전지 관련 기업에 투자하는 고위험 성장형 테마 ETF로, 최근 1년간 102.47%의 수익률을 기록했습니다. 수수료는 0.45%이며, 배당수익률은 0%로 변동성이 47.5%로 높은 편입니다. 키워드: 2차전지, 배터리, 테마, 성장, 고위험수수료 0.45%, 배당수익률: 0.0%수익률 : 102.47% / 변동성: 47.5% / MDDD : -23.19%'),
 Document(metadata={'ticker': '379810', 'name': 'KODEX 미국나스닥100', 'category': '해외주식', 'expense_ratio': 0.07, 'dividend_yield': 0.0, 'return_1y': np.float64(53.33), 'volatility': np.float64(16.58), 'mdd': np.float64(-7.34), 'risk_level': '중간', 'data_staus': 'real', 'keywords': '미국, 나스닥, 기술주, 성장, IT'}, page_content='KODEX 미국나스닥100 (해외주식): KODEX 미국나스닥100 ETF는 미국 나스닥 100 지수에 포함된 기술주 중심의 성장주에 투자하는 해외주식 ETF로, 낮은 수수료(0.07%)와 높은 1년 수익률(53.33%)을 자랑합니다. 그러나 배당수익률은 0.0%이며, 변동성은 16.58%로 다소 높은 편입니다. 키워드: 미국, 나스닥, 기술주, 성장, IT수수료 0.07%, 배당수익률: 0.0%수익률 : 53.33% / 변동성: 16.58% / MDDD : -7.34%'),
 Document(metadata={'ticker': '381180', 'name': 'TIGER 미국필라델피아반도체나스닥', 'category': '해외주식', 'expense_ratio': 0.49, 'dividend_yield': 0.0, 'return_1y': np.float64(169.62), 'volatility': np.float64(31.34), 'mdd': np.float64(-10.35), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '반도체, AI, 미국, 기술주, 고위험'}, page_content='TIGER 미국필라델피아반도체나스닥 (해외주식): TIGER 미국필라델피아반도체나스닥 ETF는 미국의 반도체 및 AI 관련 기술주에 투자하는 고위험 해외주식 ETF로, 최근 1년 동안 169.62%의 높은 수익률을 기록했습니다. 수수료는 0.49%이며, 배당수익률은 0%로 변동성이 31.34%로 나타나고 있습니다. 키워드: 반도체, AI, 미국, 기술주, 고위험수수료 0.49%, 배당수익률: 0.0%수익률 : 169.62% / 변동성: 31.34% / MDDD : -10.35%'),
 Document(metadata={'ticker': '132030', 'name': 'KODEX 골드선물(H)', 'category': '원자재', 'expense_ratio': 0.68, 'dividend_yield': 0.0, 'return_1y': np.float64(45.74), 'volatility': np.float64(30.99), 'mdd': np.float64(-24.67), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '금, 원자재, 인플레이션, 헤지, 안전자산'}, page_content='KODEX 골드선물(H) (원자재): KODEX 골드선물(H)은 금을 기초 자산으로 하는 원자재 ETF로, 인플레이션 헤지 및 안전자산으로 활용됩니다. 1년 수익률은 45.74%이며, 수수료는 0.68%로 배당수익률은 0%입니다. 키워드: 금, 원자재, 인플레이션, 헤지, 안전자산수수료 0.68%, 배당수익률: 0.0%수익률 : 45.74% / 변동성: 30.99% / MDDD : -24.67%'),
 Document(metadata={'ticker': '167860', 'name': 'KIWOOM 국고채10년레버리지', 'category': '채권', 'expense_ratio': 0.15, 'dividend_yield': 2.8, 'return_1y': np.float64(-12.55), 'volatility': np.float64(10.87), 'mdd': np.float64(-16.91), 'risk_level': '약간 낮음', 'data_staus': 'real', 'keywords': '채권, 국고채, 안전, 이자, 저위험'}, page_content='KIWOOM 국고채10년레버리지 (채권): KIWOOM 국고채10년레버리지는 안전한 국고채에 투자하는 저위험 채권 ETF로, 10년 만기 국고채의 레버리지 효과를 활용하여 이자 수익을 추구합니다. 그러나 최근 1년간 -12.55%의 수익률을 기록하며 변동성이 10.87%로 나타났습니다. 키워드: 채권, 국고채, 안전, 이자, 저위험수수료 0.15%, 배당수익률: 2.8%수익률 : -12.55% / 변동성: 10.87% / MDDD : -16.91%'),
 Document(metadata={'ticker': '214980', 'name': 'KODEX 단기채권PLUS', 'category': '채권', 'expense_ratio': 0.05, 'dividend_yield': 3.2, 'return_1y': np.float64(2.42), 'volatility': np.float64(0.21), 'mdd': np.float64(-0.08), 'risk_level': '낮음', 'data_staus': 'real', 'keywords': '단기채, 안전, 예금대안, 저위험, 이자'}, page_content='KODEX 단기채권PLUS (채권): KODEX 단기채권PLUS는 안전한 단기채권에 투자하는 ETF로, 예금 대안으로 저위험을 추구하며 3.2%의 배당수익률을 제공합니다. 1년 수익률은 2.42%이며, 변동성이 낮아 안정적인 수익을 기대할 수 있습니다. 키워드: 단기채, 안전, 예금대안, 저위험, 이자수수료 0.05%, 배당수익률: 3.2%수익률 : 2.42% / 변동성: 0.21% / MDDD : -0.08%'),
 Document(metadata={'ticker': '329200', 'name': 'TIGER 리츠부동산인프라', 'category': '부동산', 'expense_ratio': 0.29, 'dividend_yield': 4.2, 'return_1y': np.float64(23.93), 'volatility': np.float64(9.1), 'mdd': np.float64(-5.52), 'risk_level': '약간 낮음', 'data_staus': 'real', 'keywords': '리츠, 부동산, 배당, 인프라, 실물자산'}, page_content='TIGER 리츠부동산인프라 (부동산): TIGER 리츠부동산인프라는 부동산 및 인프라 관련 리츠에 투자하는 ETF로, 4.2%의 배당수익률과 23.93%의 1년 수익률을 기록하고 있습니다. 수수료는 0.29%이며, 변동성은 9.1%로 상대적으로 안정적인 실물자산 투자 옵션입니다. 키워드: 리츠, 부동산, 배당, 인프라, 실물자산수수료 0.29%, 배당수익률: 4.2%수익률 : 23.93% / 변동성: 9.1% / MDDD : -5.52%'),
 Document(metadata={'ticker': '284430', 'name': 'KODEX 200미국채혼합', 'category': '혼합', 'expense_ratio': 0.09, 'dividend_yield': 1.5, 'return_1y': np.float64(66.72), 'volatility': np.float64(13.82), 'mdd': np.float64(-7.4), 'risk_level': '약간 낮음', 'data_staus': 'real', 'keywords': '혼합, 자산배분, 균형, 중위험, 분산투자'}, page_content='KODEX 200미국채혼합 (혼합): KODEX 200미국채혼합 ETF는 중위험의 자산배분 전략을 통해 균형 잡힌 투자 포트폴리오를 제공하며, 1년 수익률이 66.72%로 높은 성과를 기록하고 있습니다. 이 ETF는 분산투자를 통해 안정성을 추구하며, 수수료는 0.09%로 낮고 배당수익률은 1.5%입니다. 키워드: 혼합, 자산배분, 균형, 중위험, 분산투자수수료 0.09%, 배당수익률: 1.5%수익률 : 66.72% / 변동성: 13.82% / MDDD : -7.4%'),
 Document(metadata={'ticker': '371460', 'name': 'TIGER 차이나전기차SOLACTIVE', 'category': '해외주식', 'expense_ratio': 0.49, 'dividend_yield': 0.0, 'return_1y': np.float64(67.72), 'volatility': np.float64(24.85), 'mdd': np.float64(-11.34), 'risk_level': '중간', 'data_staus': 'real', 'keywords': '중국, 전기차, 테마, 해외주식, 고위험'}, page_content='TIGER 차이나전기차SOLACTIVE (해외주식): TIGER 차이나전기차SOLACTIVE ETF는 중국 전기차 관련 주식에 투자하는 해외주식 ETF로, 고위험 고수익을 추구하며 1년 수익률이 67.72%에 달합니다. 수수료는 0.49%이며, 배당수익률은 0.0%입니다. 키워드: 중국, 전기차, 테마, 해외주식, 고위험수수료 0.49%, 배당수익률: 0.0%수익률 : 67.72% / 변동성: 24.85% / MDDD : -11.34%')]

In [20]:
vectorstore = LangchainFAISS.from_documents(documents, embeddings)

In [21]:
vectorstore.index.ntotal

12

In [22]:
query = '미국 기술주에 투자하고 싶어요'
vectorstore.similarity_search_with_score(query, k=3)

[(Document(id='73ca1e4d-59d1-41c5-ae91-63f4e7b30a9d', metadata={'ticker': '381180', 'name': 'TIGER 미국필라델피아반도체나스닥', 'category': '해외주식', 'expense_ratio': 0.49, 'dividend_yield': 0.0, 'return_1y': np.float64(169.62), 'volatility': np.float64(31.34), 'mdd': np.float64(-10.35), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '반도체, AI, 미국, 기술주, 고위험'}, page_content='TIGER 미국필라델피아반도체나스닥 (해외주식): TIGER 미국필라델피아반도체나스닥 ETF는 미국의 반도체 및 AI 관련 기술주에 투자하는 고위험 해외주식 ETF로, 최근 1년 동안 169.62%의 높은 수익률을 기록했습니다. 수수료는 0.49%이며, 배당수익률은 0%로 변동성이 31.34%로 나타나고 있습니다. 키워드: 반도체, AI, 미국, 기술주, 고위험수수료 0.49%, 배당수익률: 0.0%수익률 : 169.62% / 변동성: 31.34% / MDDD : -10.35%'),
  np.float32(1.1911612)),
 (Document(id='53a67661-31a2-4b5a-b6aa-d3fec5318afa', metadata={'ticker': '379810', 'name': 'KODEX 미국나스닥100', 'category': '해외주식', 'expense_ratio': 0.07, 'dividend_yield': 0.0, 'return_1y': np.float64(53.33), 'volatility': np.float64(16.58), 'mdd': np.float64(-7.34), 'risk_level': '중간', 'data_staus': 'real', 'keywords': '미국, 나스닥, 기술주, 성장, IT'}, page_content='KODEX 미국나스닥100 (해외주식): KODEX 미국나스닥100 ETF는 미국 나스닥 100 지수에 포함된 기술주 중심의 성장주에 투자하는 해외주식 ETF로, 낮은 수수료(0.07%)와 높은 1년 수익률(53.33%)을 자랑합니다. 그러나 배당수익률은 0.0%이며, 변동성은 16.58%로 다소 높은 편입니다. 키워드: 미국, 나스닥, 기술주, 성장, IT수수료 0.07%, 배당수익률: 0.0%수익률 : 53.33% / 변동성: 16.58% / MDDD : -7.34%'),
  np.float32(1.2547567)),
 (Document(id='10584c88-a7e2-467c-b00f-419510dca8eb', metadata={'ticker': '411060', 'name': 'ACE KRX금현물', 'category': '배당', 'expense_ratio': 0.01, 'dividend_yield': 3.5, 'return_1y': np.float64(59.23), 'volatility': np.float64(32.95), 'mdd': np.float64(-22.76), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '미국, 배당, 배당성장, 저비용, 안정'}, page_content='ACE KRX금현물 (배당): ACE KRX금현물 ETF는 미국 배당주에 투자하며, 저비용으로 안정적인 배당 성장을 추구합니다. 현재 배당수익률은 3.5%이며, 최근 1년간 59.23%의 수익률을 기록했습니다. 키워드: 미국, 배당, 배당성장, 저비용, 안정수수료 0.01%, 배당수익률: 3.5%수익률 : 59.23% / 변동성: 32.95% / MDDD : -22.76%'),
  np.float32(1.3617198))]

In [23]:
etf_knowledge_base = [
    {"ticker": "069500", "name": "KODEX 200", "category": "국내주식",
     "description": "KOSPI 200 지수 추적. 수수료 0.15%. 대형주 중심 분산투자.",
     "risk": "중간", "expense_ratio": 0.15},
    {"ticker": "379800", "name": "KODEX 미국S&P500TR", "category": "해외주식",
     "description": "S&P500 추적, 배당 자동 재투자. 수수료 0.05%.",
     "risk": "중간", "expense_ratio": 0.05},
    {"ticker": "461460", "name": "KODEX 미국나스닥100TR", "category": "해외주식",
     "description": "나스닥100 기술주 중심. 높은 성장성/변동성. 수수료 0.05%.",
     "risk": "높음", "expense_ratio": 0.05},
]

In [24]:
etf_names = [e['name'] + ': ' + e['description'] for e in etf_knowledge_base]
etf_names

['KODEX 200: KOSPI 200 지수 추적. 수수료 0.15%. 대형주 중심 분산투자.',
 'KODEX 미국S&P500TR: S&P500 추적, 배당 자동 재투자. 수수료 0.05%.',
 'KODEX 미국나스닥100TR: 나스닥100 기술주 중심. 높은 성장성/변동성. 수수료 0.05%.']

In [25]:
prompt = f"""다음 ETF 데이터를 보고 실제 투자자가 물어볼 법한 질문 5개를 생성하세요

ETF 목록:
{json.dumps(etf_names, ensure_ascii=False, indent=2)}

형식 : 번호. 질문"""

synthetic = llm.invoke(prompt)

In [26]:
synthetic

AIMessage(content='1. KODEX 200 ETF는 어떤 종류의 주식에 투자하나요? 대형주 중심이라고 했는데, 구체적으로 어떤 기업들이 포함되어 있나요?\n\n2. KODEX 미국S&P500TR ETF의 배당 자동 재투자 기능은 어떻게 작동하나요? 배당금이 어떻게 처리되는지 궁금합니다.\n\n3. KODEX 미국나스닥100TR ETF는 높은 성장성과 변동성을 가진다고 했는데, 이 ETF에 투자할 때 어떤 리스크를 고려해야 하나요?\n\n4. KODEX 200 ETF와 KODEX 미국S&P500TR ETF의 수수료 차이가 투자 성과에 어떤 영향을 미칠까요?\n\n5. KODEX 미국나스닥100TR ETF에 투자할 경우, 기술주 중심의 포트폴리오가 어떤 장점과 단점을 가지고 있는지 설명해 주실 수 있나요?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 193, 'prompt_tokens': 144, 'total_tokens': 337, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_a7190374f3', 'id': 'chatcmpl-DVYFZHjsUAmOerlPv1IKxdKNO1EoG', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019d9a6b-0108-7372-bcf4-ccbe2eb3cc8b-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 144, 'output_tokens': 193, 'total_tokens': 337, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [27]:
from kiwipiepy import Kiwi
from rank_bm25 import BM25Okapi

In [28]:
kiwi = Kiwi()

In [29]:
def kiwi_tokenize(text):
    tokens = kiwi.tokenize(text)
    result = []
    for token in tokens:
        if token.tag in ("SL", "SN", "NNG", "NNP"):
            result.append(token.form.lower())
            
    return result

In [30]:
kiwi_tokenize("KODEX 200 ETF는 어떤 종류의 주식에 투자하나요?")

['kodex', '200', 'etf', '종류', '주식', '투자']

In [31]:
test_text = "배당수익률 3% 이상인 미국 ETF를 추천해주세요"
kiwi_tokenize(test_text)

['배당', '수익', '3', '이상', '미국', 'etf', '추천']

In [32]:
corpus = [kiwi_tokenize(doc.page_content) for doc in documents]

In [33]:
bm25 = BM25Okapi(corpus)

In [34]:
def bm25_search(query, k=5):
    tokens = kiwi_tokenize(query)
    scores = bm25.get_scores(tokens)
    top_idx = np.argsort(scores)[::-1][:k]
    return [(documents[i], scores[i]) for i in top_idx if scores[i] > 0]

In [35]:
test_queries = [
    "KODEX 200",
    "안전한 투자 상품",
    "배당 ETF",
    "인플레이션 방어"
]

In [36]:
for q in test_queries:
    v_result = vectorstore.similarity_search(q, k=1)
    b_result = bm25_search(q, k=1)
    v_name = v_result[0].metadata['name'] if v_result else "-"
    b_name = b_result[0][0].metadata['name'] if b_result else "-"
    print(f"{q:20s} | {v_name:25s} | {b_name:25s}")

KODEX 200            | KODEX 200                 | KODEX 200
안전한 투자 상품            | KODEX 단기채권PLUS            | KODEX 단기채권PLUS
배당 ETF               | ACE KRX금현물                | ACE KRX금현물
인플레이션 방어             | KIWOOM 국고채10년레버리지         | KODEX 골드선물(H)

In [37]:
# bm25 : TF-IDF

In [38]:
# k1, b

In [39]:
query = "배당 ETF"
tokens = kiwi_tokenize(query)
params = [(0.5, 0.25), (1.5, 0.75), (2.5, 0.9)]
for k1, b in params:
    bm25_temp = BM25Okapi(corpus, k1=k1, b=b)
    scores = bm25_temp.get_scores(tokens)
    top3 = np.argsort(scores)[::-1][:3]
    print(f"k1 = {k1}, b= {b}")
    for idx in top3:
        name = documents[idx].metadata['name']
        print(f" [{scores[idx]}] {name}")

k1 = 0.5, b= 0.25
 [0.897927116360912] TIGER 2차전지테마
 [0.8961684799853846] ACE KRX금현물
 [0.8952681235017367] TIGER 차이나전기차SOLACTIVE
k1 = 1.5, b= 0.75
 [1.1587663948792346] ACE KRX금현물
 [1.078135173591938] TIGER 2차전지테마
 [1.057765717866019] TIGER 차이나전기차SOLACTIVE
k1 = 2.5, b= 0.9
 [1.3634771954524774] ACE KRX금현물
 [1.1806357049724825] TIGER 2차전지테마
 [1.1461085844371377] TIGER 차이나전기차SOLACTIVE

In [40]:
def filtered_search(vectorstore, query, filters=None, k=5, fetch_k=20):  # filters = {"expense_ratio" : 0.1, "category" : "해외주식"}
    results = vectorstore.similarity_search_with_score(query, fetch_k)
    if not filters:
        return results[:k]
    
    filtered = []
    for doc, score in results:
        match = True
        for key, condition in filters.items():
            val = doc.metadata.get(key)  # 0.49
            if isinstance(condition, dict):
                if "less_than" in condition and val > condition["less_than"]:
                    match = False
                if "greater_than" in condition and val < condition["greater_than"]:
                    match = False
            elif val != condition:
                match = False
        if match:
            filtered.append((doc, score))
    
    return filtered[:k]

In [41]:
results = filtered_search(vectorstore, "저비용 해외 ETF", 
                          filters = {"category":"해외주식", "expense_ratio" : {"less_than": 0.5}}, k=3)

In [42]:
results

[(Document(id='73ca1e4d-59d1-41c5-ae91-63f4e7b30a9d', metadata={'ticker': '381180', 'name': 'TIGER 미국필라델피아반도체나스닥', 'category': '해외주식', 'expense_ratio': 0.49, 'dividend_yield': 0.0, 'return_1y': np.float64(169.62), 'volatility': np.float64(31.34), 'mdd': np.float64(-10.35), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '반도체, AI, 미국, 기술주, 고위험'}, page_content='TIGER 미국필라델피아반도체나스닥 (해외주식): TIGER 미국필라델피아반도체나스닥 ETF는 미국의 반도체 및 AI 관련 기술주에 투자하는 고위험 해외주식 ETF로, 최근 1년 동안 169.62%의 높은 수익률을 기록했습니다. 수수료는 0.49%이며, 배당수익률은 0%로 변동성이 31.34%로 나타나고 있습니다. 키워드: 반도체, AI, 미국, 기술주, 고위험수수료 0.49%, 배당수익률: 0.0%수익률 : 169.62% / 변동성: 31.34% / MDDD : -10.35%'),
  np.float32(0.9882194)),
 (Document(id='6233d411-4d2a-436d-8d56-e8a45637d74f', metadata={'ticker': '371460', 'name': 'TIGER 차이나전기차SOLACTIVE', 'category': '해외주식', 'expense_ratio': 0.49, 'dividend_yield': 0.0, 'return_1y': np.float64(67.72), 'volatility': np.float64(24.85), 'mdd': np.float64(-11.34), 'risk_level': '중간', 'data_staus': 'real', 'keywords': '중국, 전기차, 테마, 해외주식, 고위험'}, page_content='TIGER 차이나전기차SOLACTIVE (해외주식): TIGER 차이나전기차SOLACTIVE ETF는 중국 전기차 관련 주식에 투자하는 해외주식 ETF로, 고위험 고수익을 추구하며 1년 수익률이 67.72%에 달합니다. 수수료는 0.49%이며, 배당수익률은 0.0%입니다. 키워드: 중국, 전기차, 테마, 해외주식, 고위험수수료 0.49%, 배당수익률: 0.0%수익률 : 67.72% / 변동성: 24.85% / MDDD : -11.34%'),
  np.float32(1.0651534)),
 (Document(id='53a67661-31a2-4b5a-b6aa-d3fec5318afa', metadata={'ticker': '379810', 'name': 'KODEX 미국나스닥100', 'category': '해외주식', 'expense_ratio': 0.07, 'dividend_yield': 0.0, 'return_1y': np.float64(53.33), 'volatility': np.float64(16.58), 'mdd': np.float64(-7.34), 'risk_level': '중간', 'data_staus': 'real', 'keywords': '미국, 나스닥, 기술주, 성장, IT'}, page_content='KODEX 미국나스닥100 (해외주식): KODEX 미국나스닥100 ETF는 미국 나스닥 100 지수에 포함된 기술주 중심의 성장주에 투자하는 해외주식 ETF로, 낮은 수수료(0.07%)와 높은 1년 수익률(53.33%)을 자랑합니다. 그러나 배당수익률은 0.0%이며, 변동성은 16.58%로 다소 높은 편입니다. 키워드: 미국, 나스닥, 기술주, 성장, IT수수료 0.07%, 배당수익률: 0.0%수익률 : 53.33% / 변동성: 16.58% / MDDD : -7.34%'),
  np.float32(1.1051254))]

In [50]:
def smart_filtered_search(query):
    prompt = f"""사용자 쿼리에서 ETF 검색 필터를 추출하세요.
    
    쿼리 :  {query}
    
    사용 가능한 필터 필드:
    - category : 국내주식, 해외주식, 배당, 테마 ...
    - risk_level : 낮음, 중간, 높음
    - expense_ratio : 숫자 (% "less_than"/"greater_than")
    - dividend_yield : 숫자 (%)
    - return_1y : 숫자 (%)
    - volatility : 숫자 (%)
    
    JSON 형식으로만 응답하세요. 필터가 없으면 {{}}.
    예. {{"category":"해외주식","expense_ratio":{"less_than":0.5}}}
    """
    
    response = llm.invoke([{'role' : 'user', 'content' : prompt}]).content
    try:
        if "```" in response:
            response = response.split("```")[1].replace("json", "")
        return json.loads(response)
    except Exception:
        return {}

In [51]:
test_query = "수수료 0.1% 이하이면서 배당 3% 이상인 ETF"
filters = smart_filtered_search(test_query)
filters

{'expense_ratio': {'less_than': 0.1}, 'dividend_yield': {'greater_than': 3}}

In [57]:
def smart_document_search(query, k=3):
    filters = smart_filtered_search(query)
    print(f"쿼리 : {query}, {filters}")
    print(f"필터 :{json.dumps(filters, ensure_ascii=False)}")
    
    results = filtered_search(vectorstore, query, filters = filters, k=k)
    if not results:
        print("필터 조건에 맞는 결과가 없습니다. 필터 없이 재검색....")
        results = filtered_search(vectorstore, query, k=k)
    
    print(f"결과  : {len(results)}개")
    for doc, score in results:
        m = doc.metadata
        print(m)
    
    return results

In [58]:
smart_document_search("위험 낮고 배당 2% 이상인 ETF")

쿼리 : 위험 낮고 배당 2% 이상인 ETF, {'risk_level': '낮음', 'dividend_yield': 2}
필터 :{"risk_level": "낮음", "dividend_yield": 2}
필터 조건에 맞는 결과가 없습니다. 필터 없이 재검색....
결과  : 3개
{'ticker': '305540', 'name': 'TIGER 2차전지테마', 'category': '테마', 'expense_ratio': 0.45, 'dividend_yield': 0.0, 'return_1y': np.float64(102.47), 'volatility': np.float64(47.5), 'mdd': np.float64(-23.19), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '2차전지, 배터리, 테마, 성장, 고위험'}
{'ticker': '214980', 'name': 'KODEX 단기채권PLUS', 'category': '채권', 'expense_ratio': 0.05, 'dividend_yield': 3.2, 'return_1y': np.float64(2.42), 'volatility': np.float64(0.21), 'mdd': np.float64(-0.08), 'risk_level': '낮음', 'data_staus': 'real', 'keywords': '단기채, 안전, 예금대안, 저위험, 이자'}
{'ticker': '411060', 'name': 'ACE KRX금현물', 'category': '배당', 'expense_ratio': 0.01, 'dividend_yield': 3.5, 'return_1y': np.float64(59.23), 'volatility': np.float64(32.95), 'mdd': np.float64(-22.76), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '미국, 배당, 배당성장, 저비용, 안정'}

[(Document(id='128f7929-f876-4a55-8784-a6164f462d01', metadata={'ticker': '305540', 'name': 'TIGER 2차전지테마', 'category': '테마', 'expense_ratio': 0.45, 'dividend_yield': 0.0, 'return_1y': np.float64(102.47), 'volatility': np.float64(47.5), 'mdd': np.float64(-23.19), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '2차전지, 배터리, 테마, 성장, 고위험'}, page_content='TIGER 2차전지테마 (테마): TIGER 2차전지테마 ETF는 2차전지 관련 기업에 투자하는 고위험 성장형 테마 ETF로, 최근 1년간 102.47%의 수익률을 기록했습니다. 수수료는 0.45%이며, 배당수익률은 0%로 변동성이 47.5%로 높은 편입니다. 키워드: 2차전지, 배터리, 테마, 성장, 고위험수수료 0.45%, 배당수익률: 0.0%수익률 : 102.47% / 변동성: 47.5% / MDDD : -23.19%'),
  np.float32(0.84988415)),
 (Document(id='9f2d0871-52fb-4c75-af17-ab1b3bcfd0fd', metadata={'ticker': '214980', 'name': 'KODEX 단기채권PLUS', 'category': '채권', 'expense_ratio': 0.05, 'dividend_yield': 3.2, 'return_1y': np.float64(2.42), 'volatility': np.float64(0.21), 'mdd': np.float64(-0.08), 'risk_level': '낮음', 'data_staus': 'real', 'keywords': '단기채, 안전, 예금대안, 저위험, 이자'}, page_content='KODEX 단기채권PLUS (채권): KODEX 단기채권PLUS는 안전한 단기채권에 투자하는 ETF로, 예금 대안으로 저위험을 추구하며 3.2%의 배당수익률을 제공합니다. 1년 수익률은 2.42%이며, 변동성이 낮아 안정적인 수익을 기대할 수 있습니다. 키워드: 단기채, 안전, 예금대안, 저위험, 이자수수료 0.05%, 배당수익률: 3.2%수익률 : 2.42% / 변동성: 0.21% / MDDD : -0.08%'),
  np.float32(0.88660955)),
 (Document(id='10584c88-a7e2-467c-b00f-419510dca8eb', metadata={'ticker': '411060', 'name': 'ACE KRX금현물', 'category': '배당', 'expense_ratio': 0.01, 'dividend_yield': 3.5, 'return_1y': np.float64(59.23), 'volatility': np.float64(32.95), 'mdd': np.float64(-22.76), 'risk_level': '높음', 'data_staus': 'real', 'keywords': '미국, 배당, 배당성장, 저비용, 안정'}, page_content='ACE KRX금현물 (배당): ACE KRX금현물 ETF는 미국 배당주에 투자하며, 저비용으로 안정적인 배당 성장을 추구합니다. 현재 배당수익률은 3.5%이며, 최근 1년간 59.23%의 수익률을 기록했습니다. 키워드: 미국, 배당, 배당성장, 저비용, 안정수수료 0.01%, 배당수익률: 3.5%수익률 : 59.23% / 변동성: 32.95% / MDDD : -22.76%'),
  np.float32(0.8964889))]

In [61]:
# 하이브리드 검색 : 벡터검색  + 키워드검색
def hybrid_search(query, alpha=0.5, k=5, filters=None):
    
    vec_results = vectorstore.similarity_search_with_score(query, k=20)   
    vec_scores = {} # 0 ~ 1   0.5  -> 0.5   
    for doc, dist in vec_results:
        vec_scores[doc.metadata['name']] = 1 / (1+dist)
    # vec_scores = {'TIGER 2차전지테마' : 0.5, 'TIGER 3차전지테마' : 0.9}
    
    bm25_results = bm25_search(query, k=20)
    bm25_scores = {} # 1 ~ 2   1.5  -> 0.5
    for doc, score in bm25_results:
        bm25_scores[doc.metadata['name']] = score
        
    def normalize(scores):
        if not scores:
            return scores
        
        vals = list(scores.values())
        min_, max_ = min(vals), max(vals)
        rng = max_ - min_ if max_ != min_ else 1.0
        return {k: (v-min_)/rng    for k, v in scores.items()}
    
    vec_norm = normalize(vec_scores)  # vec_norm = {'TIGER 2차전지테마' : 0.5, 'TIGER 3차전지테마' : 0.9}
    bm25_norm = normalize(bm25_scores) # bm25_norm = {'TIGER 2차전지테마' : 0.3, 'TIGER 3차전지테마' : 0.7}
    
    all_names = set(vec_norm) | set(bm25_norm)
    combined = {}
    for name in all_names:
        v = vec_norm.get(name, 0)
        b = bm25_norm.get(name, 0)
        combined[name] = alpha *  v + (1-alpha) * b  # combined = {'TIGER 2차전지테마' : 0.4, 'TIGER 3차전지테마' : ...}
    
    if filters:
        name_to_doc = {d.metadata['name'] : d  for d in documents}
        filtered = {}
        for name, score in combined.items():
            doc = name_to_doc.get(name)
            if not doc:
                continue
                
            match = True
            for key, condition in filters.items():
                val = doc.metadata.get(key)  
                if isinstance(condition, dict):
                    if "less_than" in condition and val > condition["less_than"]:
                        match = False
                    if "greater_than" in condition and val < condition["greater_than"]:
                        match = False
                elif val != condition:
                    match = False
            if match:
                filtered[name] = score
        combined = filtered
        
    sorted_results = sorted(combined.items(), key=lambda x : x[1], reverse=True)
    return sorted_results[:k]

In [64]:
query = "미국 기술 성장 ETF"
for alpha in [0.0, 0.5, 1.0]:
    results = hybrid_search(query, alpha=alpha, k=3, filters=None)
    print(results)
    names = [r[0] for r in results]
    print(f"alpha : {alpha} : {names}")

[('KODEX 미국나스닥100', np.float64(1.0)), ('TIGER 미국필라델피아반도체나스닥', np.float64(0.7827765491926837)), ('KODEX 미국S&P500', np.float64(0.508247834747415))]
alpha : 0.0 : ['KODEX 미국나스닥100', 'TIGER 미국필라델피아반도체나스닥', 'KODEX 미국S&P500']
[('KODEX 미국나스닥100', np.float64(1.0)), ('TIGER 미국필라델피아반도체나스닥', np.float64(0.769453652070173)), ('KODEX 미국S&P500', np.float64(0.5678640218105819))]
alpha : 0.5 : ['KODEX 미국나스닥100', 'TIGER 미국필라델피아반도체나스닥', 'KODEX 미국S&P500']
[('KODEX 미국나스닥100', np.float64(1.0)), ('TIGER 미국필라델피아반도체나스닥', np.float64(0.7561067342758179)), ('KODEX 미국S&P500', np.float64(0.6274545788764954))]
alpha : 1.0 : ['KODEX 미국나스닥100', 'TIGER 미국필라델피아반도체나스닥', 'KODEX 미국S&P500']

In [63]:
eval_queries = [
    {"query": "안전한 배당 ETF", "relevant": ["ACE 미국배당다우존스", "TIGER 국고채10년", "KODEX 단기채권PLUS"]},
    {"query": "미국 기술주 투자", "relevant": ["KODEX 미국나스닥100TR", "TIGER 미국필라델피아반도체"]},
    {"query": "2차전지 관련 ETF", "relevant": ["TIGER 2차전지테마"]},
    {"query": "금 투자 인플레이션 방어", "relevant": ["KODEX 골드선물(H)"]},
    {"query": "국내 대형주 인덱스", "relevant": ["KODEX 200"]},
    {"query": "부동산 배당 투자", "relevant": ["TIGER 리츠부동산인프라"]},
    {"query": "저비용 미국 ETF", "relevant": ["KODEX 미국S&P500TR", "ACE 미국배당다우존스"]},
    {"query": "채권 안정 수익", "relevant": ["TIGER 국고채10년", "KODEX 단기채권PLUS"]},
]

In [65]:
# hybrid_search, vectorstore.similairty~~~, bm25_search
def hit_rate(eval_data, search_fn, k=5):
    hits = 0
    for item in eval_data:
        results = search_fn(item['query'], k=k)
        found = [r[0] if isinstance(r, tuple) else r.metadata.get('name', '') for r in results]
        if any(rel in found for rel in item['relevant']):
            hits += 1
    return hits / len(eval_data)

In [69]:
def mrr(eval_data, search_fn, k=5):
    rr_sum = 0
    for item in eval_data:
        results = search_fn(item['query'], k=k)
        found = [r[0] if isinstance(r, tuple) else r.metadata.get('name', '') for r in results]
        for rank, name in enumerate(found, 1):
            if name in item['relevant']:
                rr_sum += 1/rank
                break
        
#         if any(rel in found for rel in item['relevant']):
#             hits += 1
    return rr_sum / len(eval_data)

In [66]:
def vec_fn(q,k=5):
    results = vectorstore.similarity_search(q, k=k)
    return [(doc.metadata['name'], 1.0) for doc in results]

def bm25_fn(q, k=5):
    results = bm25_search(q, k=k)
    return [(doc.metadata['name'], score) for doc, score in results]

def hybrid_fn(q, k=5):
    return hybrid_search(q, alpha=0.5, k=k)

In [70]:
for name, fn in [("vec", vec_fn), ("bm25", bm25_fn), ("hybrid", hybrid_fn)]:
    hr3 = hit_rate(eval_queries, fn, k=3)
    hr5 = hit_rate(eval_queries, fn, k=5)
    mrr3 = mrr(eval_queries, fn, k=3)
    mrr5 = mrr(eval_queries, fn, k=5)
    print(f"name : {name} | hr3 : {hr3} | hr5 : {hr5} | mrr3 : {mrr3} | mrr5 : {mrr5}")

name : vec | hr3 : 0.625 | hr5 : 0.75 | mrr3 : 0.625 | mrr5 : 0.65625
name : bm25 | hr3 : 0.75 | hr5 : 0.75 | mrr3 : 0.6875 | mrr5 : 0.6875
name : hybrid | hr3 : 0.75 | hr5 : 0.75 | mrr3 : 0.75 | mrr5 : 0.75

In [ ]:
# Reranking

In [ ]:
# MMR (Maximum Marginal Relevance) -> 다양한 문서를 검색

In [72]:
query = "좋은 투자 상품 추천"
sim_results = vectorstore.similarity_search(query, k=5)
mmr_results = vectorstore.max_marginal_relevance_search(query, k=5, fetch_k = 12, lambda_multi=0.5)
# mmr = lambda * similarity + (1-lambda) * diversity

for doc in sim_results:
    print(f" {doc.metadata['name']} | {doc.metadata['category']}")

print("==========================")
for doc in mmr_results:
    print(f" {doc.metadata['name']} | {doc.metadata['category']}")

 TIGER 2차전지테마 | 테마
 KODEX 단기채권PLUS | 채권
 KODEX 200미국채혼합 | 혼합
 ACE KRX금현물 | 배당
 TIGER 리츠부동산인프라 | 부동산
==========================
 TIGER 2차전지테마 | 테마
 KODEX 200 | 국내주식
 KIWOOM 국고채10년레버리지 | 채권
 ACE KRX금현물 | 배당
 KODEX 단기채권PLUS | 채권

In [75]:
def llm_rerank(query, candidates, k=5):
    name_to_doc = {d.metadata['name'] : d for d in documents}
    cand_text = ""
    for i, (name, score) in enumerate(candidates):
        doc = name_to_doc.get(name)
        if doc:
            m = doc.metadata
            cand_text += (f"{i+1}. {name} ({m['category']}) |"
                         f"수수료 {m['expense_ratio']}% | 수익률 {m['return_1y']}% | "
                          f"배당 {m['dividend_yield']}%\n")
    prompt = f"""사용자 쿼리에 가장 적합한 ETF를 순위대로 정렬하세요.
    
    쿼리 : {query}
    후보 ETF : {cand_text}
    가장 적합한 {k}개를 순위대로 번호만 응답하세요.
    예 : 3, 1, 5, 2, 4"""
    
    response = llm.invoke([{"role" : "user", "content" : prompt}]).content
    numbers = [int(x) for x in re.findall(r'\d+', response)]
    
    reranked = []
    seen = set()
    for n in numbers:
        if 1 <= n <= len(candidates) and n not in seen:
            reranked.append(candidates[n-1])
            seen.add(n)
            
    for c in candidates:
        if c not in reranked:
            reranked.append(c)
    
    return reranked[:k]

In [76]:
query = "초보자에게 안전한 ETF"
initial = hybrid_search(query, alpha=0.5, k=8)
reranked = llm_rerank(query, initial, k=5)

In [77]:
initial

[('KODEX 단기채권PLUS', np.float64(0.9868648251447245)),
 ('KIWOOM 국고채10년레버리지', np.float64(0.6932708911172552)),
 ('KODEX 골드선물(H)', np.float64(0.6080888137221336)),
 ('KODEX 200미국채혼합', np.float64(0.3896769324863797)),
 ('TIGER 2차전지테마', np.float64(0.2115126745474549)),
 ('TIGER 미국필라델피아반도체나스닥', np.float64(0.1760291341142296)),
 ('TIGER 차이나전기차SOLACTIVE', np.float64(0.17381303353197103)),
 ('KODEX 200', np.float64(0.08330609219138056))]

In [78]:
reranked

[('KODEX 단기채권PLUS', np.float64(0.9868648251447245)),
 ('KIWOOM 국고채10년레버리지', np.float64(0.6932708911172552)),
 ('KODEX 200미국채혼합', np.float64(0.3896769324863797)),
 ('KODEX 골드선물(H)', np.float64(0.6080888137221336)),
 ('TIGER 2차전지테마', np.float64(0.2115126745474549))]

In [ ]:
# contents-based filtering
# A : 짜장면 : => 짜장면 맛집
# B : 탕수육 : => 탕수육 맛집
# C : 쟁반짜장 : => 짜장면 맛집

# A : 안전추구형 => 안전한 상품만 추천
# B : 높은 수익율 =>

In [ ]:
#       Collaborative Filtering (협업 기반 추천 , 협업 기반 필터링)
#          1    2    3     4    5   6     7
# A        O    O    O
# B                       O     O
# C        O    O    ?

In [79]:
etf_data = [
    {"name": "KODEX 200",             "category": "국내주식", "expense_ratio": 0.15, "return_1y":  8.5, "risk_level": "중간", "dividend_yield": 1.8, "volatility": 15.2},
    {"name": "KODEX 미국S&P500TR",    "category": "해외주식", "expense_ratio": 0.05, "return_1y": 25.3, "risk_level": "중간", "dividend_yield": 0.0, "volatility": 18.5},
    {"name": "ACE 미국배당다우존스",   "category": "배당",     "expense_ratio": 0.01, "return_1y": 12.1, "risk_level": "낮음", "dividend_yield": 3.5, "volatility": 10.3},
    {"name": "TIGER 2차전지테마",     "category": "테마",     "expense_ratio": 0.45, "return_1y":-15.2, "risk_level": "높음", "dividend_yield": 0.0, "volatility": 35.7},
    {"name": "TIGER 국고채10년",      "category": "채권",     "expense_ratio": 0.07, "return_1y":  4.2, "risk_level": "낮음", "dividend_yield": 2.8, "volatility":  5.1},
    {"name": "KODEX 골드선물(H)",     "category": "원자재",   "expense_ratio": 0.68, "return_1y": 18.7, "risk_level": "중간", "dividend_yield": 0.0, "volatility": 20.4},
    {"name": "KODEX 미국나스닥100TR", "category": "해외주식", "expense_ratio": 0.05, "return_1y": 32.1, "risk_level": "높음", "dividend_yield": 0.0, "volatility": 25.3},
    {"name": "TIGER 미국반도체",      "category": "섹터",     "expense_ratio": 0.49, "return_1y": 45.0, "risk_level": "높음", "dividend_yield": 0.0, "volatility": 38.2},
    {"name": "KODEX 단기채권PLUS",    "category": "채권",     "expense_ratio": 0.03, "return_1y":  3.8, "risk_level": "낮음", "dividend_yield": 3.2, "volatility":  1.5},
    {"name": "TIGER 리츠부동산",      "category": "리츠",     "expense_ratio": 0.29, "return_1y":  6.5, "risk_level": "중간", "dividend_yield": 4.8, "volatility": 12.8},
    {"name": "KODEX 200TR",           "category": "국내주식", "expense_ratio": 0.12, "return_1y":  9.1, "risk_level": "중간", "dividend_yield": 0.0, "volatility": 14.9},
    {"name": "TIGER 고배당저변동",    "category": "배당",     "expense_ratio": 0.30, "return_1y":  7.2, "risk_level": "낮음", "dividend_yield": 5.2, "volatility":  8.7},
]

In [80]:
etf_df = pd.DataFrame(etf_data)
etf_df.head()

,name,category,expense_ratio,return_1y,risk_level,dividend_yield,volatility
0,KODEX 200,국내주식,0.15,8.5,중간,1.8,15.2
1,KODEX 미국S&P500TR,해외주식,0.05,25.3,중간,0.0,18.5
2,ACE 미국배당다우존스,배당,0.01,12.1,낮음,3.5,10.3
3,TIGER 2차전지테마,테마,0.45,-15.2,높음,0.0,35.7
4,TIGER 국고채10년,채권,0.07,4.2,낮음,2.8,5.1

In [81]:
risk_map = {"낮음" : 1, "중간" : 2, "높음" : 3}

def etf_to_vector(etf):
    return np.array([
        risk_map[etf['risk_level']] / 3,
        (etf['return_1y'] +30) /80,
        etf['dividend_yield'] / 6,
        etf['expense_ratio'],
        etf['volatility'] / 40
    ])

In [83]:
from numpy.linalg import norm
def cosine_sim(a, b):
    return float(np.dot(a,b) / (norm(a) * norm(b) + 1e-8))

In [84]:
item_vectors = np.array([etf_to_vector(e) for e in etf_data])
item_names = [e['name'] for e in etf_data]

In [85]:
item_vectors.shape

(12, 5)

In [86]:
def build_item_similarity(vectors):
    n = len(vectors)
    sim = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            sim[i, j] = cosine_sim(vectors[i], vectors[j])
    return sim

In [87]:
item_sim = build_item_similarity(item_vectors)

In [89]:
# item_sim
def cbf_similar_items(target_name, top_k=5):
    idx = item_names.index(target_name)
    scores = [(item_names[j], item_sim[idx, j]) for j in range(len(item_names)) if j!=idx]
    return sorted(scores, key=lambda x:x[1], reverse=True)[:top_k]

In [90]:
for name, score in cbf_similar_items('KODEX 200', top_k=5):
    print(f" {score} | {name}")

 0.9499766521932036 | KODEX 200TR
 0.9417740369716172 | KODEX 미국나스닥100TR
 0.9317615934699991 | KODEX 미국S&P500TR
 0.9242601096073657 | TIGER 미국반도체
 0.9101145298708155 | TIGER 리츠부동산

In [91]:
a = [1,2,3,5,4]
a.sort()
a

[1, 2, 3, 4, 5]

In [92]:
a = [1,2,3,5,4]
sorted(a)
a

[1, 2, 3, 5, 4]

In [95]:
etf_data

[{'name': 'KODEX 200',
  'category': '국내주식',
  'expense_ratio': 0.15,
  'return_1y': 8.5,
  'risk_level': '중간',
  'dividend_yield': 1.8,
  'volatility': 15.2},
 {'name': 'KODEX 미국S&P500TR',
  'category': '해외주식',
  'expense_ratio': 0.05,
  'return_1y': 25.3,
  'risk_level': '중간',
  'dividend_yield': 0.0,
  'volatility': 18.5},
 {'name': 'ACE 미국배당다우존스',
  'category': '배당',
  'expense_ratio': 0.01,
  'return_1y': 12.1,
  'risk_level': '낮음',
  'dividend_yield': 3.5,
  'volatility': 10.3},
 {'name': 'TIGER 2차전지테마',
  'category': '테마',
  'expense_ratio': 0.45,
  'return_1y': -15.2,
  'risk_level': '높음',
  'dividend_yield': 0.0,
  'volatility': 35.7},
 {'name': 'TIGER 국고채10년',
  'category': '채권',
  'expense_ratio': 0.07,
  'return_1y': 4.2,
  'risk_level': '낮음',
  'dividend_yield': 2.8,
  'volatility': 5.1},
 {'name': 'KODEX 골드선물(H)',
  'category': '원자재',
  'expense_ratio': 0.68,
  'return_1y': 18.7,
  'risk_level': '중간',
  'dividend_yield': 0.0,
  'volatility': 20.4},
 {'name': 'KODEX 미국나스닥100TR',
  'category': '해외주식',
  'expense_ratio': 0.05,
  'return_1y': 32.1,
  'risk_level': '높음',
  'dividend_yield': 0.0,
  'volatility': 25.3},
 {'name': 'TIGER 미국반도체',
  'category': '섹터',
  'expense_ratio': 0.49,
  'return_1y': 45.0,
  'risk_level': '높음',
  'dividend_yield': 0.0,
  'volatility': 38.2},
 {'name': 'KODEX 단기채권PLUS',
  'category': '채권',
  'expense_ratio': 0.03,
  'return_1y': 3.8,
  'risk_level': '낮음',
  'dividend_yield': 3.2,
  'volatility': 1.5},
 {'name': 'TIGER 리츠부동산',
  'category': '리츠',
  'expense_ratio': 0.29,
  'return_1y': 6.5,
  'risk_level': '중간',
  'dividend_yield': 4.8,
  'volatility': 12.8},
 {'name': 'KODEX 200TR',
  'category': '국내주식',
  'expense_ratio': 0.12,
  'return_1y': 9.1,
  'risk_level': '중간',
  'dividend_yield': 0.0,
  'volatility': 14.9},
 {'name': 'TIGER 고배당저변동',
  'category': '배당',
  'expense_ratio': 0.3,
  'return_1y': 7.2,
  'risk_level': '낮음',
  'dividend_yield': 5.2,
  'volatility': 8.7}]

In [97]:
j

NameError: name 'j' is not defined

In [100]:
def cbf_diverse(target_name, top_k=5):
    idx = item_names.index(target_name)
    scores = [(j, item_sim[idx, j]) for j in range(len(item_names)) if j!=idx]
    scores.sort(key = lambda x : x[1], reverse=True)
    
    result, seen_cats = [], set()
    for j, score in scores:
        print(j)
        cat = etf_data[j]['category']
        if cat in seen_cats:
            continue
        result.append((item_names[j], round(score, 3), cat))
        seen_cats.add(cat)
        if len(result) >= top_k:
            break
    return result

In [101]:
cbf_diverse('KODEX 200', top_k=5)

10
6
1
7
9
4

[('KODEX 200TR', np.float64(0.95), '국내주식'),
 ('KODEX 미국나스닥100TR', np.float64(0.942), '해외주식'),
 ('TIGER 미국반도체', np.float64(0.924), '섹터'),
 ('TIGER 리츠부동산', np.float64(0.91), '리츠'),
 ('TIGER 국고채10년', np.float64(0.889), '채권')]